### PR TITLE
TASK: fixed and updated Dover-Gabe courier robot.

### PR DESCRIPTION
**Pull request by bobbyjim**

### CODE REVIEW

**Comment by cmcknight** [comment]
Merging. Will be part of 31 Oct 2021 deployment.

**Comment by cmcknight** [comment]
Two things I just noticed:

1. There was no cost in the PR (I’ve fixed that)
2. On the wiki, the cost is listed as:   MCrMCr 15.3.

Best regards, and thanks again for your help!

Chuck

**Comment by cmcknight** [comment]
One more thing.

While I have avoided putting too much game detail in the catalog, preferring to point to other sources (such as the wiki, rule books etc.), It is possible to embed just about anything in the description so if you choose to embed statistics, lists, etc., it’s easily done as HTML tables, unordered/ordered lists, etc.

I didn’t remember if I mentioned that in the various discussions although I do remember saying something about not wanting to deprive Marc, et al, of any sales revenue by putting too much of the game mechanics in the descriptions. 🤔

**Comment by bobbyjim** [comment]
Ha.  OK.  Well catalogs generally don't have lots of detail.  I figure most
robot listings won't have histories and such... this one might be an
exception.

**Comment by cmcknight** [comment]
Yeah, but I wanted to ensure that I had mentioned that the product descriptions really aren’t terribly restricted. :-)

**Pull request merged**
